version: '3.8'

services:
  coji-api:
    container_name: coji-api
    hostname: coji-api
    build: .
    env_file:
      - .api-env
    volumes:
      - ./api:/app
    ports:
      - 8000:8000
    restart: always
    networks:
      - network
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    user: root
    restart: always
    networks:
      - network
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
      - ./prometheus-web.yml:/etc/password/web.yml
    command:
#      - '--web.config.file=/etc/password/web.yml'
      - '--query.lookback-delta=1m'
      - '--config.file=/etc/prometheus/prometheus.yml'
    links:
      - pushgateway
    depends_on:
      - pushgateway
    ports:
      - 9090:9090

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: always
    expose:
      - 9091
    ports:
      - 9091:9091
    networks:
      - network
networks:
  network: