global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:

scrape_configs:
  - job_name: 'coji-api-metrics'
    static_configs:
      - targets: ['coji-api:8000']
